#Store all your config's here.
#added to gitignore so will not be syned

#Backup in ~/Desktop/config.py_backup

shodan_api=""
bing_api=""
github_access_token="4ef16d35f968cd0f2c1fea61d78a55ad3c181459"
builtwith_api=""
censysio_id="d58fd5ea-1dc0-46d3-8d80-01fd640d6c3e"
censysio_secret="MzBsq3mSmxJBJNfQB4a2rFnSrygGlY6S"
facebook_access_token = ""
flickr_api=""
google_api=""
google_cse_key="AIzaSyBT0twCE8PukNutWN8h9lou7x2huttGMQE"
google_cse_cx = "011149421707785710311:2bw6eodznml"
hashes_api=""
ipinfodb_api=""
jigsaw_api=""
jigsaw_password=""
jigsaw_username=""
linkedin_api=""
linkedin_secret=""
pwnedlist_api=""
pwnedlist_iv=""
pwnedlist_secret=""
reddit_id = ""
reddit_secret = ""
spyonweb_access_token = "N8M6Oz1HDlZP"
twitter_consumer_key=""
twitter_consumer_secret=""
twitter_access_token = ""
twitter_access_token_secret = ""
zoomeyeuser = ""
zoomeyepass = ""
clearbit_apikey = ""
emailhunter="cd6cdbf692b8f717dcce985494d9f7fcfb46765e"
jsonwhois=""
instagram_token = ""
instagram_client_id = ""
instagram_client_secret = ""
fullcontact_api = ""
mailboxlayer_api = ""
virustotal_public_api =""
urlscanio_api = ""
